### ISSUE TITLE
Update author name in LICENSE

### ISSUE THREAD

**Issue by cvan** [flysonic10/aframe-passthrough#2]
Nice work here with this project! 👍 

I noticed the [`LICENSE`](https://github.com/flysonic10/aframe-passthrough/blob/master/LICENSE) has `Kevin Ngo` as the author. Just thought I'd mention it in case you wanted to change it mention your name instead.

**Comment by willwnekowicz** [comment]
Good point! I think I had just used some starter scaffolding for this. Thanks
