### ISSUE TITLE
Error loading example

### ISSUE THREAD

**Issue by evhan55** [flysonic10/aframe-passthrough#4]
Hello!

I tried to run your example in the README but I get this error:
`TypeError: MediaStreamTrack.getSources is not a function`

Any idea? Thanks!
Evelyn

**Comment by willwnekowicz** [comment]
Hey, I had merged in a fix for that, but forgot to build the new distribution for it. Just pushed that.

Grab the latest master and try again!

**Comment by evhan55** [comment]
Hi!

It still doesn't seem to work at this link?
https://flysonic10.github.io/aframe-passthrough/basic/
